### ISSUE TITLE
[MVP] Epic

### ISSUE THREAD

**Issue by Enoch-Kim** [earning-rightly/whilabel#1]
MVP 버전을 개발하기 위한 TODO List와 큰 기능 단위 이슈를 모아둔 에픽

## TODO List

- [ ] 공통
  - [ ] application 기능 정의 (MVP 버전)
  - [ ] 시장 조사
  - [x] #2
  - [ ] 개발 일정 계획

- [x] #5
  - [ ] 설계
  - [ ] 위스키 API 조사
  - [ ] 데이터 가공 및 적재

- [ ] API
  - [ ] 설계
  - [ ] 개발
  - [ ] 연동
  - [ ] 배포

- [x] #3
  - [x] #4
  - [ ] 개발환경 설정
  - [x] #11
  - [ ] 배포
